/** Renders an AuditReport as a Markdown document (Developer/Security report). */

import { summarize } from '../core/scoring.js';
import type { AuditReport, Finding } from '../core/types.js';

const SEV_EMOJI: Record<Finding['severity'], string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
  info: '⚪',
};

function findingBlock(f: Finding): string {
  const lines: string[] = [];
  lines.push(`### ${SEV_EMOJI[f.severity]} ${f.title}`);
  lines.push('');
  lines.push(`- **Severity:** ${f.severity.toUpperCase()}  •  **Status:** ${f.status}  •  **Probability:** ${f.probability}  •  **Category:** ${f.category}`);
  lines.push(`- **Risk:** ${f.risk}`);
  lines.push(`- **Why it matters:** ${f.whyItMatters}`);
  lines.push(`- **Technical detail:** ${f.technical}`);
  lines.push(`- **Business impact:** ${f.businessImpact}`);
  if (f.owasp?.length) lines.push(`- **OWASP:** ${f.owasp.join(', ')}`);
  if (f.cve?.length) lines.push(`- **CVE:** ${f.cve.join(', ')}`);
  lines.push(`- **Remediation:** ${f.remediation}`);
  lines.push(`- **Estimated fix time:** ${f.estimatedFixTime}`);
  if (f.exampleCode) {
    lines.push('');
    lines.push('```');
    lines.push(f.exampleCode);
    lines.push('```');
  }
  if (f.references.length) lines.push(`- **References:** ${f.references.map((r) => `<${r}>`).join(', ')}`);
  lines.push('');
  return lines.join('\n');
}

export function toMarkdown(report: AuditReport): string {
  const s = summarize(report);
  const out: string[] = [];

  out.push(`# Aegis Security & Scalability Audit`);
  out.push('');
  out.push(`**Target:** ${report.target}  `);
  out.push(`**Scanned:** ${report.scannedAt}  `);
  out.push(`**Mode:** ${report.meta.passiveOnly ? 'Passive only' : 'Passive + Active (authorized)'}  `);
  out.push(`**Engine:** v${report.meta.engineVersion}`);
  out.push('');
  out.push(`## Overall Score: ${report.overall.score} / 100 (${report.overall.grade})`);
  out.push('');

  out.push('| Category | Score | Grade |');
  out.push('| --- | ---: | :---: |');
  for (const c of report.categories) {
    const ran = Object.values(c.findingCounts).reduce((a, b) => a + b, 0);
    if (ran === 0) continue;
    out.push(`| ${c.category} | ${c.score} | ${c.grade} |`);
  }
  out.push('');

  out.push('## Executive Summary');
  out.push('');
  out.push(`This audit evaluated **${report.target}** across ${report.modules.filter((m) => m.ok).length} modules. ` +
    `It identified **${s.critical} critical**, **${s.high} high**, **${s.medium} medium**, and **${s.low} low** severity issues, with **${s.passed} checks passing**. ` +
    `The overall posture scored **${report.overall.score}/100 (${report.overall.grade})**.`);
  out.push('');
  const top = report.findings.filter((f) => f.status === 'fail' && (f.severity === 'critical' || f.severity === 'high')).slice(0, 5);
  if (top.length) {
    out.push('**Top priorities:**');
    out.push('');
    for (const t of top) out.push(`1. ${SEV_EMOJI[t.severity]} ${t.title} — _${t.estimatedFixTime}_`);
    out.push('');
  }

  out.push('## Findings');
  out.push('');
  const failing = report.findings.filter((f) => f.status !== 'pass');
  for (const f of failing) out.push(findingBlock(f));

  const passed = report.findings.filter((f) => f.status === 'pass');
  if (passed.length) {
    out.push('## Passing Checks');
    out.push('');
    for (const p of passed) out.push(`- ✅ ${p.title}`);
    out.push('');
  }

  out.push('---');
  out.push('_Generated by Aegis Auditor. This is a defensive assessment; active checks run only with explicit authorization._');
  return out.join('\n');
}
