/** Deterministic ticket generation (GitHub Issues / Jira) from a report. */

import type { AuditReport } from '../core/types.js';
import { actionableFindings } from './shared.js';
import type { Ticket } from './types.js';

const SEV_TO_JIRA: Record<string, string> = { critical: 'Highest', high: 'High', medium: 'Medium', low: 'Low', info: 'Lowest' };

/** One ticket per actionable finding, formatted for the target tracker. */
export function generateTickets(report: AuditReport, format: 'github' | 'jira'): Ticket[] {
  const host = safeHost(report.target);
  return actionableFindings(report).map((f) => {
    const priority = format === 'jira' ? `\n*Priority:* ${SEV_TO_JIRA[f.severity] ?? 'Medium'}` : '';
    const body =
      `**Target:** ${host}\n` +
      `**Severity:** ${f.severity} · **Probability:** ${f.probability} · **Est. fix:** ${f.estimatedFixTime}${priority}\n\n` +
      `### Risk\n${f.risk}\n\n` +
      `### Why it matters\n${f.whyItMatters}\n\n` +
      `### Technical detail\n${f.technical}\n\n` +
      `### Business impact\n${f.businessImpact}\n\n` +
      `### Remediation\n${f.remediation}\n` +
      (f.exampleCode ? `\n\`\`\`\n${f.exampleCode}\n\`\`\`\n` : '') +
      (f.owasp?.length ? `\n**OWASP:** ${f.owasp.join(', ')}\n` : '') +
      (f.cve?.length ? `**CVE:** ${f.cve.join(', ')}\n` : '') +
      (f.references.length ? `\n**References:**\n${f.references.map((r) => `- ${r}`).join('\n')}\n` : '') +
      `\n_Generated by Aegis Auditor (finding \`${f.id}\`)._`;

    const labels = ['aegis', `severity:${f.severity}`, `category:${f.category}`];
    if (f.owasp?.length) labels.push(...f.owasp.map((o) => `owasp:${o.split(':')[0]}`));

    return { title: `[${f.severity.toUpperCase()}] ${f.title}`, body, labels, severity: f.severity };
  });
}

function safeHost(target: string): string {
  try {
    return new URL(target).hostname;
  } catch {
    return target;
  }
}
